### ISSUE TITLE
سلام ممنون لطفا پکیج را مطابق نمونه بسازید

### ISSUE THREAD

**Issue by vahidalvandi** [saeedvaziry/payir#1]
لطفا از
guzzle 
و مطابق نمونه زیر کار کنید

https://github.com/payping/payping-php-client

**Comment by saeedvz** [comment]
پکیج فعلی استاندارد و کاملا پایدار هستش و نیازی به تبدیل به نمونه مورد نظر نمی باشد.
در صورت تمایل میتونید کلون بگیرید و خودتون تبدیل کنید.
