### ISSUE TITLE
خطا در ارسال اطلاعات به Pay.ir. لطفا از برقرار بودن اینترنت و در دسترس بودن pay.ir اطمینان حاصل کنید

### ISSUE THREAD

**Issue by waltun** [saeedvaziry/payir#2]
سلام خسته نباشید
من در لاراول پکیج رو نصب کردم و روی حالت تست وقتی تراکنش موفق رو میزنم همه چی به درستی کار میکنه، اما وقتی روی تراکنش نا موفق میزنم این ارور بالا رو میده در صورتی که من واسش شرط گذاشتم که اگر استاتوس برابر 0 بود ارور خودم رو تو صفحه نشون بده
`if (request('status') == 0) {
       return redirect(route('profile.orders'))->with('failed_pay', 'تراکنش با خطا مواجه شد');
}`
یا حتی به این صورت 
`if ($verify['status'] == 0) {
        return redirect(route('profile.orders'))->with('failed_pay', 'تراکنش با خطا مواجه شد');
 }`

**Comment by saeedvaziry** [comment]
@webnoti سلام.
این یک اکسپشن هست و زمانی رخ میده که سرور شما قادر به ارتباط با شبکه پرداخت پِی نباشه.
این خطای مهمی هست و حتما با مسئول سرورتون بررسی کنید که با شبکه پرداخت پی ارتباط داشته باشه سرورتون.
همچنین برای هندل کردن این خطا میبایست از
try catch
استفاده کنید
